version: 0.2

phases:
  pre_build:
    commands:
      - echo $(grep version package.json | awk -F\" '{print $4}')
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region ap-southeast-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t codebuild:$(grep version package.json | awk -F\" '{print $4}') .
      - docker tag codebuild:$(grep version package.json | awk -F\" '{print $4}') 469447658758.dkr.ecr.ap-southeast-1.amazonaws.com/codebuild:$(grep version package.json | awk -F\" '{print $4}')      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 469447658758.dkr.ecr.ap-southeast-1.amazonaws.com/codebuild:$(grep version package.json | awk -F\" '{print $4}')